#!/bin/bash
# This script is part of Booth.
# It checks whether the given resource (service) still has a chance
# to run on the local cluster, so that booth knows whether to
# acquire the ticket here.

set -e

service="${1:?Need a resource name as first argument.}"


# We expect an output like
#   p_dummy        (ocf::pacemaker:Dummy): Started geo-rz2-a 

if crm_simulate --ticket-grant "$BOOTH_TICKET" --simulate --live-check |
	sed -n '/^Revised cluster status:/,$p' |
	egrep "^[[:space:]]+$service[[:space:]]+\(.*\):[[:space:]]+Started ([^[:space:]]+) *$" >/dev/null
then
	# can be started - we're done.
	exit 0
fi


# Some error occured.
# Try to help the admin with a bit of diagnostic.
#
# disallow ms-resources, ie. only primitives wanted here
if ! crm_resource -l | grep -v ":" | grep "$service" ; then
	ha_logger "Defined resource '$service' in $BOOTH_CONF_PATH is not a primitive??"
fi

exit 1

